#!/bin/bash

JOKES=(
    "Why don't scientists trust atoms? Because they make up everything!"
    "What do you call fake spaghetti? An impasta!"
    "Why did the scarecrow win an award? Because he was outstanding in his fiel>
    "I told my wife she was drawing her eyebrows too high. She looked surprised>
    "Why did the math book look sad? Because it had too many problems."
    "Why did the computer go to therapy? It had too many bytes from its past!"
    "What do you call a bear with no teeth? A gummy bear!"
    "How do you organize a space party? You planet!"
     "Why did the golfer bring two pairs of pants? In case he got a hole in one>
    "What did one wall say to the other wall? I’ll meet you at the corner!"
    "What do you call cheese that isn't yours? Nacho cheese!"
    "Why don’t skeletons fight each other? They don’t have the guts!"
    "How does a penguin build its house? Igloos it together!"
    "Why did the bicycle fall over? Because it was two-tired!"
    "What do you get when you cross a snowman and a vampire? Frostbite!"
)




QUOTES=(
    "The best way to predict the future is to invent it. - Alan Kay"
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Sw
    "The only way to do great work is to love what you do. - Steve Jobs"
    "Success is not the key to happiness. Happiness is the key to success. - Al
    "What lies behind us and what lies before us are tiny matters compared to w
    "RISE UP AND STAY STRONG 🗿"
)

function show_menu {
        echo "Choose an option"
        echo "1. Get a random joke"
        echo "2. Get a random quote"
        echo "3. Exit "
        echo -n "Select an option (1-3)"
}

while true; do
        show_menu
read -r choice

        case $choice in

        1)

                RANDOM_JOKE=${JOKES[RANDOM % ${#JOKES[@]}]}
                echo ""
                echo "Here's a random boring Joke"
        echo "$RANDOM_JOKE"
        echo ""
;;


        2)





